### ISSUE TITLE
Enable 2d axisymmetric cases

### ISSUE THREAD

**Issue by arvedes** [precice/openfoam-adapter#228]
For 2d cases with a wedge for axisymmetric simulation this causes an error. I'd suggest to change that to a warning.

https://github.com/precice/openfoam-adapter/blob/a95da52062c2f503ce58d9509c3e47f5efdbf149/Interface.C#L156

**Comment by DavidSCN** [comment]
That's indeed something I did not yet consider. I'm a bit afraid that a warning is not enough as OpenFOAM has a very verbose output and also preCICE (potentially also the adapter) prints out information on the terminal so that the warning disappears rather quick. I would rather introduce a boolean configuration parameter in order to only pass through this line in case it was explicitly enabled.

**Comment by arvedes** [comment]
That would also be an option. I implemented the warning here, it works well: https://github.com/arvedes/openfoam-adapter

**Comment by Habaw27** [comment]
Hello arvedes
I tried to run a 2D axisymmetric case with the modification you suggested but still an error occurs from Utilities.C file and stops.
How did you solve this issue?
Thank you

**Comment by arvedes** [comment]
My simulations worked well with this fix. What error message do you get?
Did you try to run without coupling?

**Comment by Habaw27** [comment]
Dear

I hope this message finds you well. I wanted to express my gratitude for
your prompt response to my previous inquiry. I am currently engaged in a
simulation project involving a modified version of the perpendicular flap
tutorial, employing the coupling of OpenFOAM and deal.II through the
preCICE library.

In my initial tests using the 2D case, I encountered no issues and was able
to successfully run the simulation. However, when I transitioned to a 2D
axisymmetric configuration, I began encountering errors. Interestingly, I
managed to resolve the openFOAM fluid part's issues last night.

However, my current challenge lies in the deal.II solid part, which is
producing an inconsistent geometry error. The error message is as follows:

" An error occurred in line <227> of file
</home/habib/build/dealii-adapter/include/adapter/adapter.h> in function
    void Adapter::Adapter<dim, VectorType,
ParameterClass>::initialize(const dealii::DoFHandler<dim, dim>&, const
VectorType&, VectorType&) [with int dim = 2; VectorType =
dealii::Vector<double>; ParameterClass = Parameters::AllParameters]
The violated condition was:
    dim == precice.getDimensions()
Additional information:
    The dimension of your solver needs to be consistent with the dimension
    specified in your precice-config file. In case you run one of the
    tutorials, the dimension can be specified via cmake -D DIM=dim . "

I am reaching out to inquire if you have previously encountered this
particular error and if you might have insights into potential solutions.
Your experience and guidance would be greatly appreciated.

Additionally, if you have any recommendations beyond the use of deal.II for
addressing such challenges, I would be grateful to hear your suggestions.

Once again, I thank you for your valuable time and assistance. I look
forward to your response.

Best regards,

Habib

**Comment by arvedes** [comment]
Dear Habib,
Good to hear that you resolved the OpenFOAM issue. Unfortunately, I don't have any experience with deal.II myself, so I may not be able to offer much assistance. However, I would suggest asking for help on the forum at https://precice.discourse.group/c/news/5. I hope you're able to find a solution to your issue soon!
Best,
Arved

**Comment by Habaw27** [comment]
Dear arvedes,
Thank you very much for you help. I will ask my problems on the forum you suggested.
Regards
Habib
